version: 1
combine: and
morphology:
  open: 1
  close: 3
classes:
  1:
    name: center_lane
    color_bgr:
    - 0
    - 255
    - 255
    priority: 1
    hls:
      min:
      - 20
      - 60
      - 60
      max:
      - 36
      - 255
      - 255
    hsv:
      min:
      - 15
      - 60
      - 60
      max:
      - 51
      - 255
      - 255
    ycrcb:
      min:
      - 24
      - 120
      - 0
      max:
      - 255
      - 205
      - 180
  2:
    name: left_solid
    color_bgr:
    - 255
    - 80
    - 0
    priority: 2
    hls:
      min:
      - 71
      - 163
      - 0
      max:
      - 179
      - 247
      - 201
    hsv:
      min:
      - 61
      - 0
      - 150
      max:
      - 117
      - 36
      - 255
    ycrcb:
      min:
      - 177
      - 0
      - 0
      max:
      - 255
      - 255
      - 255
  3:
    name: right_solid
    color_bgr:
    - 0
    - 80
    - 255
    priority: 3
    hls:
      min:
      - 71
      - 163
      - 0
      max:
      - 179
      - 247
      - 201
    hsv:
      min:
      - 61
      - 0
      - 150
      max:
      - 117
      - 36
      - 255
    ycrcb:
      min:
      - 177
      - 0
      - 0
      max:
      - 255
      - 255
      - 255
  4:
    name: road
    color_bgr:
    - 80
    - 80
    - 80
    priority: 5
    hls:
      min:
      - 11
      - 95
      - 0
      max:
      - 116
      - 208
      - 52
    hsv:
      min:
      - 10
      - 0
      - 0
      max:
      - 106
      - 48
      - 255
    ycrcb:
      min:
      - 0
      - 0
      - 0
      max:
      - 247
      - 242
      - 255
  5:
    name: shortcut
    color_bgr:
    - 255
    - 0
    - 255
    priority: 4
    hls:
      min:
      - 0
      - 87
      - 0
      max:
      - 60
      - 165
      - 49
    hsv:
      min:
      - 0
      - 0
      - 0
      max:
      - 179
      - 255
      - 255
    ycrcb:
      min:
      - 105
      - 0
      - 0
      max:
      - 255
      - 255
      - 255
